Repository nextcloud/nextcloud-talk-recording, pull requests merged in 2025-04, with the labels that each got.

#33 feat: add support for specifying browser executable directly
  AUTHORS.md
  docs/installation.md
  server.conf.in
  src/nextcloud/talk/recording/Config.py
  src/nextcloud/talk/recording/Participant.py
  src/nextcloud/talk/recording/Service.py
Labels: 3. to review

#28 Remove unneeded visit to main Nextcloud server page
  src/nextcloud/talk/recording/Participant.py
Labels: 3. to review, bug

#40 Set a unique name for each Pylint check
  .github/workflows/lint-python.yml
Labels: 3. to review, bug, github_actions

#43 Disable linter check for "too-many-positional-arguments"
  pyproject.toml
Labels: 3. to review, bug
